[project]
name = "dev-tools-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "ipykernel>=6.30.0",
    "keplergl>=0.3.7",
    "pandas>=2.3.1",
]
